Lab/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('lab_4.urls')),
    path('portfolio', include('lab_7.urls')),
    path('books/', include('lab_8.urls')),
    path('admin/', admin.site.urls),
]

lab_4/urls.py
from django.urls import *

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('schedules', views.schedules, name='schedules'),
    path('schedules/list', views.schedulelist, name='schedulelist'),
    re_path('deleteschedule/(?P<idnum>\d+)/', views.deleteschedule, name='deleteschedule'),
]

lab_7/urls.py
from django.urls import *

from . import views

app_name = 'lab_7'
urlpatterns = [
    path('', views.portfolio, name='portfolio')
]

lab_8/urls.py
from django.urls import *

from . import views

app_name = 'lab_8'
urlpatterns = [
    path('', views.book_list, name='book_list'),
    path('<title>', views.books, name='booksdict')
]

lab_4/models.py
from django.db import models
from django.utils import timezone
from datetime import *

# Create your models here.

class Schedule(models.Model):
    hari = models.CharField(max_length=30)
    tanggal = models.DateField()
    jam = models.TimeField()
    nama_kegiatan = models.CharField(max_length=50)
    tempat = models.CharField(max_length=30)
    kategori = models.CharField(max_length=30)

    def __str__(self):
        return self.nama_kegiatan

lab_7/models.py
from django.db import models

# Create your models here.

lab_8/models.py
from django.db import models

# Create your models here.

lab_4/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule

        fields = ['hari', 'tanggal', 'jam', 'nama_kegiatan', 'tempat', 'kategori']

        widgets = {
            'hari' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text'}),
            'tanggal' : forms.DateInput(attrs={'class' : 'form-control', 'type' : 'date'}),
            'jam' : forms.TimeInput(attrs={'class' : 'form-control', 'type' : 'time'}),
            'nama_kegiatan' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text'}),
            'tempat' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text'}),
            'kategori' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text'}),
        }

lab_4/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Schedule
from .forms import ScheduleForm


def index(request):
    return render(request, 'index.html')
# Create your views here.

#Add schedules
def schedules(request): 
    if request.method == 'POST':
        form = ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('schedules/list')
        else:
            return HttpResponseRedirect('schedules')
    else:
        form = ScheduleForm()
        return render(request, 'schedules.html', {'form' : form}) 
        #Mengeluarkan form yang digenerate oleh forms.py di shcedules.html

#See list of schedules
def schedulelist(request):
    schd = Schedule.objects.all()
    return render(request, 'schedulelist.html', {'table' : schd})

def deleteschedule(request, idnum):
    Schedule.objects.get(id=idnum).delete()
    schd = Schedule.objects.all()
    return render(request, 'schedulelist.html', {'table' : schd})

lab_7/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def portfolio(request):
    return render(request, 'portfolio.html')

lab_8/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
import json
import requests

# Create your views here.
# def books(request):
#     r = requests.get("https://www.googleapis.com/books/v1/volumes?q='manusia'")
#     r = r.json()
#     items = r['items'] #google api store item details as list of dictionary
#     shown_items = []
#     for i in items:
#         temp = {
#             'preview' : i['volumeInfo']['imageLinks']['thumbnail'],
#             'title' : i['volumeInfo']['title']
#         }
#         getAuthor = i['volumeInfo'].get('authors', 'Unknown')
#         temp['authors'] = getAuthor
#         shown_items.append(temp)    #remove unnecessary details that is not shown
#     return JsonResponse({'items' : shown_items})

def books(request, title):
    r = requests.get("https://www.googleapis.com/books/v1/volumes?q=intitle:" + title)
    r = r.json()
    return JsonResponse(r)

def book_list(request):
    return render(request, 'books.html')

lab_4/templates/base.html
{% load static %}
<div>
    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
        <a class="navbar-brand" href="#" style="padding-left: 20px">
        <img src="{% static 'lab_4/images/Logo.png' %}" width="40" height="40" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAlt">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAlt">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/#home">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/#about">ABOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/#rec">TRACK RECORDS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/#contacts">CONTACTS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'schedules' %}">SCHEDULES</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lab_7:portfolio' %}">PORTFOLIO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lab_8:book_list' %}">BOOKS</a>
                </li>
            </ul>
        </div>
    </nav>
</div>

lab_4/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'lab_4/css/styles.css'%}"/>

    <title>Rhendy Rivaldo</title>
  </head>
  
  <body data-spy="scroll" data-target=".navbar" data-offset="50">
    {% include "base.html" %}
    <div id="home" class="bg_main">
      <div class="container text-center centered">
        <div class="row">
          <div class="col-md-6">
            <div>
              <h1 class="title_white">Hello World!</h1>
            </div>
            <div class="parag_white">
              <p>Welcome to my first ever website! You are going to know more about me here. 
                Hope you like this website, enjoy!</p>
            </div>
          </div>
          <div class="col-md-6 resp_img">
            <div style="text-align: center">
              <img src="{% static 'lab_4/images/main_compboy.png' %}" class="img-responsive alt="Yeah!">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="about" class="bg_about">
      <div class="container centered">
        <div class="row abt_pad">
          <div class="col-md-6">
            <div>
              <h1 class="title_black">ABOUT ME</h1>
            </div>
            <div class="parag_black">
              <p><br>My name is Rhendy. I was born in Temanggung, March 30th 1999, so I am 20 now. I am the first child of three, and I am currently a student of the Faculty of Computer Science, Universitas Indonesia.</p>
              <p>I like to play videogames, and I really love to watch movies, especially mystery-thriller or horror movies. I also like comedies, it can make the audience’s life more colorful.</p>
            </div>
          </div>
          <div class="col-md-6 resp_img">
            <div style="text-align: center">
              <img src="{% static 'lab_4/images/MyPhoto1.jpg' %}" class="img-thumbnail img-responsive myphoto" alt="Me">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="rec" class="bg_records">
      <div class="container centered">
        <div>
          <h1 class="title_white" style="text-align: right; padding-top: 20px">MORE OF ME</h1>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div>
              <h4 style="text-align: center; padding-top: 20px">EDUCATION</h4>
            </div>
            <div class="rec_small_bg">
              <div class="centered">
                <p>
                  TK Pelita Hati <br>(2002-2005)<br><br>
                  SD Pelita Hati <br>(2005-2011)<br><br>
                  SMP St. Bellarminus <br>(2011-2014)<br><br>
                  SMAN 3 Jakarta <br>(2014-2017)<br><br>
                  Faculty of Computer Science, <br>Universitas Indonesia <br>(2017-present)
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div>
              <h4 style="text-align: center; padding-top: 20px">ORGANIZATION</h4>
            </div>
            <div class="rec_small_bg">
              <div class="centered">
                <p>
                  Departemen Kajian dan Aksi Strategis<br>
                  BEM Fasilkom UI 2018<br><br>
                  Departemen Keuangan Keluarga Mahasiswa Buddhis (KMBUI) XXVI
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div>
              <h4 style="text-align: center; padding-top: 20px">COMMITTEE</h4>
            </div>
            <div class="rec_small_bg">
              <div class="centered">
                <p>
                  25th Computers Get Together<br><br>
                  Wisuda Genap Fasilkom UI 2018<br><br>
                  Pemilihan Raya Fasilkom UI 2018<br><br>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="contacts" class="bg_contacts">
      <div class="container centered">
        <div>
            <h1 class="title_black" style="text-align: center">CONTACTS</h1>
        </div>
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4">
            <div class="cont_mrg">
              <ul style="list-style-type: none">
                <li class="thumb_margin">
                  <img class="socmed_thumbnailg" src="{% static 'lab_4/images/gmail.png' %}">
                </li>
                <li class="thumb_margin">
                  <img class="socmed_thumbnail" src="{% static 'lab_4/images/insta.png' %}">
                </li>
                <li class="thumb_margin">
                  <img class="socmed_thumbnail" src="{% static 'lab_4/images/line.png' %}">
                </li>
                <li class="thumb_margin">
                  <img class="socmed_thumbnail" src="{% static 'lab_4/images/whatsapp.png' %}">
                </li>
              </ul>
            </div>
            <div class="cont_mrg socmed_list">
              <ul style="list-style-type: none">
                <li class="parag_blacksoc">rhendyrvld@gmail.com</li>
                <li class="parag_blacksoc">rhendyrivaldo</li>
                <li class="parag_blacksoc">rhendyrivaldo</li>
                <li class="parag_blacksoc">0857 8890 0014</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

lab_4/templates/schedulelist.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/8f7ecc8fdd.js" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'lab_4/css/styles.css'%}"/>

    <title>Schedules</title>

    <style>
      #redir_list{
        color: #ffffff;
      }
    </style>
  </head>

  <!-----------------------------------------Schedule List--------------------------------------------->
  <body class="bg_sched">
    {% include 'base.html' %}
    <div class="container montserrat_font">
      <h1 class="title_white" style="margin-top: 90px">Schedule List</h1>
        <div class="table-responsive">
          <table id='schedules' class="table table-striped table-light" style="margin-top: 40px">
            <thead>
              <tr>
                  <th scope="col">Kegiatan</th>
                  <th scope="col">Tanggal</th>
                  <th scope="col">Hari</th>
                  <th scope="col">Jam</th>
                  <th scope="col">Tempat</th>
                  <th scope="col">Kategori</th>
              </tr>
            </thead>
            <tbody>
              {% if table %}
                {% for schedule in table %}
                <tr>
                  <th scope="row">{{ schedule.nama_kegiatan }}</th>
                  <td>{{ schedule.tanggal }}</td>
                  <td>{{ schedule.hari }}</td>
                  <td>{{ schedule.jam }}</td>
                  <td>{{ schedule.tempat }}</td>
                  <td>{{ schedule.kategori }}</td>
                  <td><a href="{% url 'deleteschedule' idnum=schedule.id %}"><i class="fas fa-minus-circle"></i></a></td>
                </tr>
                {% endfor %}
              {% else %}
                <td colspan="6">There are currently no schedule planned</td>
              {% endif %}
            </tbody>
        </table>
      </div>
      <div style="padding-bottom:200px">
        <a class="btn btn-info float-right" id="redir_list" href="{% url 'schedules' %}">Add schedule</a>
      </div>
    </div>
  </body>
</html>

lab_4/templates/schedules.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'lab_4/css/styles.css'%}"/>
    <style>
        #redir_list{
            color: #ffffff;
        }
    </style>
    <title>Add schedules</title>
  </head>

  <!-----------------------------------------Add schedule-------------------------------------------->
  <body class="bg_sched" data-spy="scroll" data-target=".navbar" data-offset="50">
      {% include 'base.html' %}
      <div class="container montserrat_font">
        <h1 class="title_white" style="text-align: right; margin-top: 95px">Add Schedule</h1>
        <div class="row">
            <div class="col-sm-6 mx-auto" style="margin: 40px 0px">
                <form action="{% url 'schedules' %}" method="POST">
                    {% csrf_token %}
                        {{ form }}
                        <br>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-info float-right">Submit</button>
                        <a class="btn btn-info float-right" id="redir_list" href="{% url 'schedulelist' %}"> See my schedules</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
  </body>
</html>

lab_7/templates/portfolio.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
        <script src="{% static 'lab_7/js/actions.js' %}"></script>
        <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
        <link rel="stylesheet" type="text/css" href="{% static 'lab_7/css/styles.css'%}"/>
        <title>Portfolio</title>
    </head>
    
    <body class="bg_prtf">
        {% include "base.html" %}
        <!-- <div class="container montserrat_font">
            <div class="row">
                <div class="col-md-12" style="margin-top: 95px; margin-bottom: 95px;">
                    <h1 class="title_white prtf_h1">A Little Portfolio</h1>
                    <a class="btn btn-primary float-right" id="btn-mode">Default theme</a>
                </div>
            </div>
        </div> -->
        <div class="container1" style="margin: 120px auto">
            <div>
                <a class="btn btn-primary small-btn-text float-right" id="btn-mode">Default theme</a>
            </div>
            <div class="accordiontitle" style="margin-bottom: 50px">
                <h1 class="title_white">A Little Portfolio</h1>
            </div>
            <div class="accordionhead">
                <a href=#>Aktivitas</a>
                <div class="content">
                    <ul style="list-style: none;">
                        <li>PPW</li>
                        <li>POK</li>
                        <li>Banjut</li>
                    </ul>
                </div>
            </div>
            <div class="accordionhead">
                <a href=#>Pengalaman Organisasi/Kepanitaan</a>
                <div class="content">
                    <ul style="list-style: none;">
                        <li>25th Computers Get Together</li>
                        <li>Departemen Keuangan KMBUI XXVI</li>
                        <li>Departemen Kajian dan Aksi Strategis BEM Fasilkom UI 2018</li>
                        <li>Wisuda Genap Fasilkom UI 2018</li>
                        <li>Pemilihan Raya Fasilkom UI 2018</li>
                    </ul>
                </div>
            </div>
            <div class="accordionhead">
                <a href=#>Prestasi</a>
                <div class="content">
                    <ul style="list-style: none;">
                        <li>Coming Soon</li>
                    </ul>
                </div>
            </div>
        </div>
    </body>

lab_8/templates/books.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'lab_8/js/function.js' %}"></script>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'lab_8/css/styles.css'%}"/>

    <title>Books</title>

  </head>

  <!-----------------------------------------Schedule List--------------------------------------------->
<body class="bg_books">
    {% include 'base.html' %}
    <div class="container montserrat_font">
        <h1 class="title_white" style="margin-top: 90px">It's (not) a library!</h1>
        <div class="form-inline">
            <input type="text" class="form-control" id="input" placeholder="Search for books here...">
            <a class="btn btn-light float-right " id="search_button" onclick="getInput()">Search</a>
        </div>
        <div class="table-responsive">
            <table id='books' class="table table-striped table-light" style="margin-top: 40px">
                <thead>
                    <tr>
                        <th scope="col">No</th>
                        <th scope="col">Preview</th>
                        <th scope="col">Title</th>
                        <th scope="col">Author</th>
                    </tr>
                </thead>
                <tbody id="book_table">
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>